[package]
name = "visualization"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
tokio = "1.29.1"
serde = "1.0.164"
charming = { version = "0.4.0", features = ["ssr"] }
serde_json = "1.0.133"
askama = "0.12.1"
lazy_static = "1.5.0"

[profile.release]
debug = true

